In [1]:
import numpy as np

def activate_function(x):
    return 1 / (1 + np.exp(-x))


inputs = [0.5, -0.2, 0.1]


In [2]:
inputs = [0.5, -0.2, 0.1]

In [3]:
weights = np.random.normal(-1, 1, (2, len(inputs))) #Random weights
print(weights)

[[-3.42510656 -1.9874603  -1.63937576]
 [-2.4565637  -0.68665585 -0.38658479]]


In [4]:
bias = np.random.normal(-1, 1, len(inputs)) #Random bias
print(bias)

[-1.18562995 -2.06894056 -1.17496196]


In [5]:
result = sum((inputs * weights) + bias)

In [6]:
activate_function(result)

array([ 0.00490738,  0.02651794,  0.07225737])