In [1]:
import numpy as np

def sigmoid_activate_function(x):
    return 1 / (1 + np.exp(-x))


inputs = [0.5, -0.2, 0.1]


In [2]:
weights = np.random.normal(-1, 1, (2, len(inputs))) #Random weights
print(weights)

[[-1.70202786  0.37724257 -1.4839826 ]
 [-0.47832681 -0.82659334 -2.07684343]]


In [3]:
bias = np.random.normal(-1, 1, len(inputs)) #Random bias
print(bias)

[-0.28236924 -0.51023903 -0.57300145]


In [4]:
result = sum((inputs * weights) + bias)

In [5]:
sigmoid_activate_function(result)

array([ 0.16044567,  0.2828014 ,  0.18211468])